### PR TITLE
update more pages and functions.

### PR DESCRIPTION
**Pull request by FuZifei**
Hey guys,
I updated the home page which add new function of upload and download.
I need the corresponding servlet code. The name of the servlet is set in advance.  Feel free to change it, of course, it's better to use the name I wrote before.
Please leave a message if you have any questions.

### CODE REVIEW

**Comment by FuZifei** [comment]
> 
> 
> What is bootstrap? I saw files named bootstrap.js and bootstrap.min.js, what's that for?

Bootstrap is a front-end development framework, the difference between these two is bootstrap.* is compiled css and js, and bootstrap.min.* is a compressed version

**Comment by FuZifei** [comment]
> 
> 
> I would like to know the details of the servlet corresponding to these pages.



> 
> 
> I'm amazed you had finished upload&download in the front-end, that's reduce so much stress of us.
> thx soooooooo much!
> 👍



> 
> 
> I would like to know the details of the servlet corresponding to these pages.

As an example, when you click the upload button in the home file, the FileServlet of the backend is called, and the corresponding upload method is called by the judgment of the parameter “action”. Its role is to operate the database to write file information to the database. The other button are consistent with this logic. There are many methods in FileServlet, which are all corresponding to the functions that need to be presented to the user after clicking the button on the page.

**Comment by FuZifei** [comment]
> 
> 
> I would like to know the details of the servlet corresponding to these pages.

As an example, when you click the upload button in the home file, the FileServlet of the backend is called, and the corresponding upload method is called by the judgment of the parameter “action”. Its role is to operate the database to write file information to the database. The other button are consistent with this logic. There are many methods in FileServlet, which are all corresponding to the functions that need to be presented to the user after clicking the button on the page

**Comment by FuZifei** [comment]
> 
> 
> I am curious about the purpose of guard-index.js(3 functions?), will be grateful if some explanation can be given.

This is a JavaScript file, which is embedded in home.html. The function is to call the backend FileServlet to render all the existing file information and corresponding delete function.

**Comment by LJShuo** [comment]
> > What is bootstrap? I saw files named bootstrap.js and bootstrap.min.js, what's that for?
> 
> Bootstrap is a front-end development framework, the difference between these two is bootstrap.* is compiled css and js, and bootstrap.min.* is a compressed version

Got that! So, there are some common-used encapsulated functions in bootstrap? like a library?

**Comment by FuZifei** [comment]
> 
> 
> > > What is bootstrap? I saw files named bootstrap.js and bootstrap.min.js, what's that for?
> > 
> > 
> > Bootstrap is a front-end development framework, the difference between these two is bootstrap.* is compiled css and js, and bootstrap.min.* is a compressed version
> 
> Got that! So, there are some common-used encapsulated functions in bootstrap? like a library?

yes

**Pull request merged**
