### PR TITLE
part of file-related functionalities

### PR DESCRIPTION
**Pull request by LJShuo**
I completed part of file operations like add, delete and search which related to the search button in the home.html. But I am not sure the logic is perfect. And I am working on how to combine with upload functionality. And I am not sure if it is the right way to design a file javabean like this? PLZ give me some suggestions!

### CODE REVIEW

**Comment by LJShuo** [comment]
> I think the JavaBean part is fine. Can this function be seen as creating files online and writing it?

No online real-time modification so far. I have tried it before, but not work well :(

**Comment by lhnneve** [comment]
Well the logic is pretty clear as we expected. I believe that the connection to our web application is non-error. Still, I reckon that for the same File which should have the same NAME where now we have only various ID. That may not be the original idea as we planned. I will try to amend it. =)

**Comment by FuZifei** [comment]
> 
> 
> > I think the JavaBean part is fine. Can this function be seen as creating files online and writing it?
> 
> No online real-time modification so far. I have tried it before, but not work well :(

Fine, maybe just download and modify the files is enough. So all the file information contains in the database right? Btw, what's the primary key of that table?

**Comment by LJShuo** [comment]
> > > I think the JavaBean part is fine. Can this function be seen as creating files online and writing it?
> > 
> > 
> > No online real-time modification so far. I have tried it before, but not work well :(
> 
> Fine, maybe just download and modify the files is enough. So all the file information contains in the database right? Btw, what's the primary key of that table?

Yes , including the file content in base64. The primary key is the id of file, but I think I should change later on

**Comment by LJShuo** [comment]
> Well the logic is pretty clear as we expected. I believe that the connection to our web application is non-error. Still, I reckon that for the same File which should have the same NAME where now we have only various ID. That may not be the original idea as we planned. I will try to amend it. =)

Yeah, this is a problem, we will handle it later on.

**Pull request merged**
